### ISSUE TITLE
urls_to_html opens unescaped variables to XSS

### ISSUE THREAD

**Issue by gambry** [vstelmakh/url-highlight-twig-extension#10]
### Overview
The library documentation doesn't advise enough about using `urls_to_html` filter opening to XSS attacks.

### Problem
In fact developers may rely on twig auto escaping for their security and want to use this library to simply convert URLs to html anchors. But as soon as they use the filter any input is now considered safe.

### Solution
It would be nice for the default behaviour to NOT consider the whole input string safe, but this may be a back-compatibility issue and so at least would be better to advice user to use `{{ text|escape|urls_to_html }}` on unsafe strings relying on twig auto escape

**Comment by vstelmakh** [comment]
Escaping output - is not a responsibility of the library. Library don’t know if the input is safe or not, it’s just looking for urls. So it should be a decision of the developer to escape input, if necessary.

Finding urls in html escaped input is a bit more tricky.
- For example:
\<p>http://example.com?a=b<﻿/p>

- Escaped will look like:
\&lt;p\&gt;http://example.com?a=b&lt;/p&gt﻿;

Which will be wrongly highlighted, as you see GitHub do ☝️

To avoid cases like this - encoder should be specified. Which is described in [configuration](https://github.com/vstelmakh/url-highlight-twig-extension#configuration) section, right below the first usage example. And usage example there looks exactly as a solution you suggested.

**Comment by gambry** [comment]
Hi @vstelmakh , thanks for your answer.

> Escaping output - is not a responsibility of the library.

I agree.

> Library don’t know if the input is safe or not, it’s just looking for urls

I would agree, but `vstelmakh/url-highlight-twig-extension` [is wrongly assuming the input is already safe](https://github.com/vstelmakh/url-highlight-twig-extension/blob/master/src/UrlHighlightExtension.php#L33) when it shouldn't make this assumption. In fact twig default behaviour is to auto escape, so a developer relying on auto escape when using `{{ text }}` is in big trouble when doing `{{ text | urls_to_html }}`, without any advice.

I understand changing this from code perspective is quite difficult, as it would mean refactoring the whole library. That's why all I'm suggesting is to put in the documentation the `urls_to_html` filter considers the input string safe and it is developer responsibility to make sure it is. Something like:

_**Warning: the filter considers the input string being already safe, and it will print any HTML tag in it. It is developer responsability to sanitise the input before using it with `urls_to_html`**_

And then the reference to handle escapes with encored is already there, so all good.

**Comment by vstelmakh** [comment]
Maybe you are right :thinking:. Should not harm to explicitly mention this in documentation. Thanks for the input.

You are welcome to post a PR with this change, if you want to. If not - than I will do it a bit later :wink:

**Comment by gambry** [comment]
@vstelmakh amazing thanks. PR ☝️ .
(it flags a change at EOF, but must be Github editors removing EOL at EOF 🤷‍♂️ ).

**Comment by vstelmakh** [comment]
Thanks for the PR. Please change target branch to source repo, as it points to the fork now, so I can't merge it :smile:

**Comment by gambry** [comment]
🤦, sorry. Done.

**Comment by vstelmakh** [comment]
[PR](https://github.com/vstelmakh/url-highlight-twig-extension/pull/11) merged. Closing this one.
